### ISSUE TITLE
tutorial doc bug

### ISSUE THREAD

**Issue by zhujiajunbryan** [thunlp/OpenDelta#42]
Hi, I noticed that there're some bugs exists in the BM train [tutorial file](https://github.com/thunlp/OpenDelta/blob/main/examples/tutorial/2_with_bmtrain.sh), would you mind if you could modify it in the future?

### argument bug

returns:```2_with_bmtrain.py: error: unrecognized arguments: --delta_type low_rank_adapter```

### delta model visualization bug
returns:
```  
File "./2_with_bmtrain.py", line 132, in get_model
od.Visualization(model).structure_graph()
AttributeError: module 'opendelta' has no attribute 'Visualization'
```
in order to reproduce it, I worked with  ```open delta                      0.3.2```

### lowrank adapter with bert
when using bert with lowrankadapter, returns
```
AttributeError: str(forward() got an unexpected keyword argument 'output_pooler_output')
        The LowRankAdapterModel requires a dummy_inputs to be passed through the model to understand the dimensionality of each tensor in the computation graph. 
         The BertModel Class has no dummy_inputs, and automatically created dummy_inputs failed.
         Refer to `https://opendelta.readthedocs.io/en/latest/notes/faq.html` for detail.
```
### lora with bert
```
Traceback (most recent call last):
  File "./2_with_bmtrain.py", line 371, in <module>
    main()
  File "./2_with_bmtrain.py", line 360, in main
    tokenizer, model, optimizer, lr_scheduler = setup_model_and_optimizer(args)
  File "./2_with_bmtrain.py", line 204, in setup_model_and_optimizer
    model = get_model(args)
  File "./2_with_bmtrain.py", line 135, in get_model
    delta_model = LoraModel(backbone_model=model, modified_modules=['project_q', 'project_k'], backend='bmt')
  File "/root/miniconda3/lib/python3.8/site-packages/opendelta/delta_models/lora.py", line 136, in __init__
    self.add_all_delta_to_backbone(self.backbone_model,
  File "/root/miniconda3/lib/python3.8/site-packages/opendelta/basemodel.py", line 213, in add_all_delta_to_backbone
    self.update_module(backbone, key)
  File "/root/miniconda3/lib/python3.8/site-packages/opendelta/delta_models/lora.py", line 143, in update_module
    parallel_module = self.new_module_like(child_module=child_ref)
  File "/root/miniconda3/lib/python3.8/site-packages/opendelta/delta_models/lora.py", line 151, in new_module_like
    in_features, out_features = child_module.in_features, child_module.out_features
  File "/root/miniconda3/lib/python3.8/site-packages/bmtrain-0.1.8-py3.8-linux-x86_64.egg/bmtrain/layer.py", line 12, in __getattr__
    ret = super().__getattr__(name)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Linear' object has no attribute 'in_features'
```

### incorrect installation commands

```
root@container-bb51118b3c-1fa0644b:~/OpenDelta/examples/tutorial# pip install git+git@github.com:OpenBMB/ModelCenter.git
ERROR: Invalid requirement: 'git+git@github.com:OpenBMB/ModelCenter.git'
Hint: It looks like a path. File 'git+git@github.com:OpenBMB/ModelCenter.git' does not exist.
```
thanks for your contribution to the open source community; if you got some time in the feature, it would be great to update the tutorial
with regards jiajun

**Comment by Achazwl** [comment]
- argument bug: Fixed in 4315b83c8eb3d5602d9dfeb18fa6cef9f246315a, it only changes the tutorial file, you can modify it yourself without reinstalling OpenDelta; delta model visualization bug: Fixed by `from bigmodelvis import Visualization` and use `Visualization` instead of `od.Visualization`.
- bert related bug: Use model_center >= 1.0.0 would be ok.
- installation commands: For ModelCenter, `pip install model-center >= 1.0.0`; For BMTrain, `git clone https://github.com/OpenBMB/BMTrain.git` and `python3 setup.py install` locally, as its latest version has not been released to pypi currently.
