### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by Mryangkaitong** [thunlp/OpenDelta#49]
>>> from opendelta import AutoDeltaModel, AutoDeltaConfig
/root/anaconda3/lib/python3.8/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.14) or chardet (2.1.1)/charset_normalizer (2.1.1) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/search/ai/kaitongyang/cpm_ant_plus/CPM-Live/cpm-live/OpenDelta/opendelta/__init__.py", line 13, in <module>
    from .utils.saving_loading_utils import SaveLoadMixin
  File "/search/ai/kaitongyang/cpm_ant_plus/CPM-Live/cpm-live/OpenDelta/opendelta/utils/saving_loading_utils.py", line 9, in <module>
    from DeltaCenter import OssClient
  File "/root/anaconda3/lib/python3.8/site-packages/delta_center_client-0.0.4-py3.8.egg/DeltaCenter/__init__.py", line 3, in <module>
    from .client import Client, help
  File "/root/anaconda3/lib/python3.8/site-packages/delta_center_client-0.0.4-py3.8.egg/DeltaCenter/client.py", line 5, in <module>
    import oss2
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/root/anaconda3/lib/python3.8/site-packages/oss2-2.15.0-py3.8.egg/oss2/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/root/anaconda3/lib/python3.8/site-packages/oss2-2.15.0-py3.8.egg/oss2/models.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/root/anaconda3/lib/python3.8/site-packages/oss2-2.15.0-py3.8.egg/oss2/utils.py", line 32, in <module>
  File "/root/anaconda3/lib/python3.8/site-packages/Crypto/Cipher/__init__.py", line 7, in <module>
    from Crypto.Cipher._mode_ctr import _create_ctr_cipher
  File "/root/anaconda3/lib/python3.8/site-packages/Crypto/Cipher/_mode_ctr.py", line 35, in <module>
    from Crypto.Util.number import long_to_bytes
  File "/root/anaconda3/lib/python3.8/site-packages/Crypto/Util/number.py", line 387
    s = pack('>I', n & 0xffffffffL) + s
                                 ^
SyntaxError: invalid syntax

**Comment by helloxcq** [comment]
Try `pip3 install pyrebase4`, as is not valid in Python 3.x.
