### ISSUE TITLE
Soft prompt for BERT

### ISSUE THREAD

**Issue by chengjiali** [thunlp/OpenDelta#7]
Hi, I was training soft prompt for BERT and met the following error:

```
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenDelta/opendelta/delta_models/soft_prompt.py", line 90, in pre_forward
    inputs_embeds = self.raw_embedding(input_ids)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_text_classification.py", line 652, in <module>
    main()
  File "train_text_classification.py", line 561, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/user/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 1332, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 1891, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/transformers/trainer.py", line 1923, in compute_loss
    outputs = model(**inputs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenDelta/opendelta/utils/decorate.py", line 47, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenDelta/opendelta/basemodel.py", line 502, in _caller
    args, kwargs = delta_module.pre_forward(*args, **kwargs)
  File "/home/user/anaconda3/lib/python3.7/site-packages/OpenDelta/opendelta/delta_models/soft_prompt.py", line 92, in pre_forward
    raise RuntimeError("neither inputs_embeds nor input_ids is specified.")
RuntimeError: neither inputs_embeds nor input_ids is specified.
```
I used the example configs and `example_text_classification/run_glue.py` to launch the job.
Could you help me with this? Thank you!

**Comment by ShengdingHu** [comment]
We have fixed this, and will push it to the main branch after checking.
